version: "3.9"

services:
  web:
    build: .
    container_name: agent_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
  db:
    image: postgres:15
    container_name: agent_db
    environment:
      POSTGRES_DB: agentdb
      POSTGRES_USER: agentuser
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
